<x-landing-layout>
    <div class="p-20 text-left mx-auto">
        <h1 class="text-3xl font-bold">Terms of Use</h1><br>
        <p><strong>Welcome to the RealtyHive, LLC (&ldquo;RealtyHive,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) website, a division of Micoley.com, LLC. These Terms of Use (&ldquo;Terms&rdquo;) govern your use of https://www.RealtyHive.com (the &ldquo;Site&rdquo;) and any other websites, social media applications, interactive features and other resources controlled by Micoley.com, LLC (the &ldquo;Services&rdquo;). Please read the Terms carefully. By using the Site, you agree that you have read, understand and agree to be bound by these Terms. If you do not agree to the Terms below, please do not use the Site.</strong></p>
        <p>&nbsp;</p>
        <h3><strong>User Responsibilities.</strong></h3>
        <p>By using the Site and Services, you agree to abide by all applicable local, state, national, and international laws and regulations, in connection with your use of the Site. You acknowledge and agree that your use of the Internet and access to the Site is solely at your own risk.</p>
        <h5 style="text-align: left;"><br /><strong>User Submissions</strong></h5>
        <p><br /><strong>We value the integrity of our Site.</strong></p>
        <p>When posting information on the Site or through the Services, you warrant and represent that you either own or otherwise control all of the rights to the material, including without limitation, all the rights necessary for you to provide, post, upload, input, or submit the material, or that your use of the material is a fair use. You agree that you will not knowingly and with intent to defraud provide material and misleading false information. You represent and warrant also that the material you supply does not violate these Terms, and that you indemnify RealtyHive, its affiliates, agents, co-branders or other partners and representatives harmless from and against any and all claims, damages, losses, costs or expenses (including reasonable attorneys' fees and disbursements) in relation to user submissions.</p>
        <p>&nbsp;</p>
        <h3><strong>Accounts, Passwords and Security.</strong></h3>
        <p>&nbsp;</p>
        <p><em><strong>Age Restrictions</strong></em></p>
        <p>The Site and Services are not intended for users under the age of 18. If, in your jurisdiction, the age of majority is above the age of 18, you must be above the age of majority in your jurisdiction to use the Site and Services.</p>
        <p>&nbsp;</p>
        <p><em><strong>Maintaining Security</strong></em></p>
        <p>You are wholly responsible for maintaining the security and confidentiality of your account and password. You are wholly responsible for any and all activities that are conducted through your account. Please notify us immediately of any unauthorized use of your account or any other breach of security. Although RealtyHive has taken measures to ensure the confidentiality of communications and materials transmitted to or from the Site, please understand that no data transmission can be guaranteed to be 100% secure.</p>
        <p><br /><em><strong>Membership Cancellation</strong></em></p>
        <p>If you would like to cancel your membership, please do so by sending an email to <a title="Contact RealtyHive" href="mailto:email@realtyhive.com" target="_blank">email@realtyhive.com</a>. &nbsp;</p>
        <h3><br /><strong>Termination.</strong></h3>
        <p>You agree that RealtyHive, in its sole discretion, may terminate your account or use of the Site, and remove and discard any content within the Site, at any time and for any reason. You agree that any actions taken under this section may be effective without prior notice to you.</p>
        <p>&nbsp;</p>
        <h3><strong>Privacy Policy.</strong></h3>
        <p>By accessing the Site, you agree that you are accepting the Privacy Policy of the Site.</p>
        <h3><br /><strong>Third Party Sites and Content.</strong></h3>
        <p>Terms and agreements entered into by users of this Site and real estate agents are not endorsed, recommended, or otherwise the responsibility of RealtyHive.</p>
        <p><br />Any opinions, advice, statements, services, advertisements, offers, or other information or content made available through the Site by third parties are those of the respective authors, distributors or advertisers and not RealtyHive. Neither RealtyHive, its affiliates, nor any third party content providers guarantee the accuracy, completeness, or reliability of the advice, statements services, advertisements, offers, or other content displayed on the Site. You use the Site and Services at your own risk. RealtyHive does not assume responsibility for third-party content displayed on the Site.</p>
        <h3><br /><strong>Indemnification.</strong></h3>
        <p>By using this Site, you agree to indemnify and hold the RealtyHive and its affiliates, agents, co-branders or other partners and representatives harmless from and against any and all claims, damages, losses, costs or expenses (including reasonable attorneys' fees and disbursements) which arise directly or indirectly out of or from (i) your breach of these Terms; (ii) any allegation that any user submission materials infringe or otherwise violate the copyright, trade secret, trademark or other intellectual property rights of a third party; and (iii) your access or use of the Site.</p>
        <h3><br /><strong>Disclaimer.</strong></h3>
        <p>THE SITE, AND ANY CONTENT, TOOLS, PRODUCTS OR SERVICES DISPLAYED, ACCESSED OR OBTAINED ON OR THROUGH THE SITE IS PROVIDED "AS IS", "AS AVAILABLE", AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</p>
        <p><br />TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. WE DO NOT WARRANT THAT THIS SITE; INFORMATION, CONTENT, MATERIALS, PRODUCTS OR SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THIS SITE; THEIR SERVERS; OR E-MAIL SENT FROM US ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
        <p><br />UNLESS PROHIBITED BY APPLICABLE LAW, WE SHALL NOT, UNDER ANY CIRCUMSTANCES, BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH USE OF THE SITE, WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE, PRODUCT LIABILITY OR OTHERWISE), OR ANY OTHER PECUNIARY LOSS, WHETHER OR NOT THE SITE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. UNDER NO CIRCUMSTANCES SHALL THE SITE BE LIABLE TO YOU FOR ANY AMOUNT.</p>
        <p><br />SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS AND DISCLAIMERS MAY NOT APPLY TO YOU. TO THE EXTENT THAT WE MAY NOT, AS A MATTER OF APPLICABLE LAW, DISCLAIM ANY IMPLIED WARRANTY OR LIMIT LIABILITIES, THE SCOPE AND DURATION OF SUCH WARRANTY AND THE EXTENT OF OUR LIABILITY WILL BE THE MINIMUM PERMITTED UNDER SUCH APPLICABLE LAW.</p>
        <h3><br /><strong>Limitation of Liability.</strong></h3>
        <p>REALTYHIVE IS NOT RESPONSIBLE OR LIABLE TO YOU OR ANYONE ELSE FOR ANY LOSS OR INJURY OR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR OTHER DAMAGES UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO (I) THE USE OF OR INABILITY TO USE THE SITE; (II) ANY CONTENT CONTAINED ON THE SITE; (III) STATEMENTS OR CONDUCT POSTED OR MADE PUBLICLY AVAILABLE ON THE SITE; (IV) ANY PRODUCT OR SERVICE PURCHASED OR OBTAINED THROUGH THE SITE; (V) ANY ACTION TAKEN IN RESPONSE TO OR AS A RESULT OF ANY INFORMATION AVAILABLE ON THE SITE; (VI) ANY DAMAGE CAUSED BY LOSS OF ACCESS TO, DELETION OF, FAILURE TO STORE, FAILURE TO BACK UP, OR ALTERATION OF ANY CONTENT ON THE SITE; OR (VII) ANY OTHER MATTER RELATING TO THE SITE. IN NO EVENT SHALL THE TOTAL LIABILITY OF REALTYHIVE OR ITS LICENSORS, AFFILIATES TO YOU FOR ANY AND ALL DAMAGES, LOSSES, AND CAUSES OF ACTION EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR USING ANY OF THE SITE.</p>
        <p><br />SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS AND DISCLAIMERS MAY NOT APPLY TO YOU. TO THE EXTENT THAT WE MAY NOT, AS A MATTER OF APPLICABLE LAW, DISCLAIM ANY IMPLIED WARRANTY OR LIMIT LIABILITIES, THE SCOPE AND DURATION OF SUCH WARRANTY AND THE EXTENT OF OUR LIABILITY WILL BE THE MINIMUM PERMITTED UNDER SUCH APPLICABLE LAW.</p>
        <h3><br /><strong>Copyright Information.</strong></h3>
        <p>The Site contains copyrighted materials, trademarks, service marks, logos and other proprietary content, including, but not limited to, text, software, sound, photographs, images, videos and graphics (the &ldquo;Content&rdquo;). You are only permitted to use the Content as expressly authorized by RealtyHive. Neither the Terms nor the use of the Site transfers rights, titles or interest in the Site or the Content to you. Third party licensors retain their respective Intellectual Property rights on and to the Site and Content.</p>
        <p><br />In accordance with The Digital Millennium Copyright Act of 1998 (the "DMCA") copyright owners, who believe that material appearing on the Site infringes on their rights under the U.S. copyright law, may contact us. If you believe that any materials hosted by the Site infringe on your copyright, you or your agent may send a notice requesting that the material be removed or access to it be blocked. If you believe in good faith that a notice of copyright infringement has been wrongly filed against you in connection with this Site, the DMCA permits you to send to RealtyHive a counter-notice; see http://www.loc.gov/copyright for details. False claims under the DMCA may result in legal penalties against you.</p>
        <br>
        <strong>Restrictions on Use.</strong><br> We grant you a limited access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with our express written consent. This access does not include any resale or commercial use of this site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. This Site or any portion of this Site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without our express written consent.</li>
        </ol>
        <p>&nbsp;</p>
        <h3><strong>Governing Law.</strong></h3>
        <p>These Terms and the relationship between you and RealtyHive shall be governed by and construed in accordance with the laws of the State of Wisconsin, without regard to its conflict of law provisions. You and RealtyHive irrevocably agree to submit to the personal and exclusive jurisdiction of the federal and state courts located within the State of Wisconsin, and waive any jurisdictional, venue or inconvenient forum objections to such courts.</p>
        <h3><br /><strong>Waiver of Class Action and Mandatory Arbitration.</strong></h3>
        <p>By using this Site and the Services, you agree that you expressly, irrevocably, and unconditionally waive any right to proceed in a class action or other representative capacity for any proceedings arising out of or relating to any disputes with RealtyHive.</p>
        <p><br />By using this Site and the Services, you agree that any and all disputes relating to these Terms, the Privacy Policy, or your registration to the Services, shall be resolved by binding arbitration in accordance with the rules of the American Arbitration Association before an independent arbitrator. This arbitration obligation applies regardless of whether the claim or dispute involves a tort, fraud, misrepresentation, product liability, negligence, violation of a statute, or any other legal theory. The location of arbitration shall be Green Bay, Wisconsin.</p>
        <h3><br /><strong>Waiver and Severability.</strong></h3>
        <p>The failure of RealtyHive to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is found by a court of competent jurisdiction to be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severed and shall not affect the validity and enforceability of any remaining provisions.</p>
        <h3><br /><strong>Modifications.</strong></h3>
        <p>RealtyHive may, in its sole and absolute discretion, change these Terms from time to time. All changes to the Terms or the Privacy Policy will be effective when posted, and we will provide notification of such changes to you via contact information you may have provided to the Site upon registration. Your continued use of the Site following any changes to the Terms or the Privacy Policy will constitute your agreement to be bound by such changes. If you object to any such changes, your sole recourse shall be to cease using the Site.</p>
        <h3><br /><strong>Contact Information.</strong></h3>
        <p>Should you need to contact the RealtyHive for any reason regarding these Terms, please contact us by email at <a title="Email RealtyHive" href="mailto:email@realtyhive.com" target="_blank">email@realtyhive.com</a> or by mail at:</p>
        <p><br /><strong>RealtyHive, LLC</strong></p>
        <p>445 Cardinal Lane, Suite 102</p>
        <p>Green Bay, WI 54313</p>
        <p>&nbsp;</p>
    </div>
</x-landing-layout>